language: go
sudo: required
dist: precise

notifications:
   email: false

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

go:
  - 1.11

script: 
  - sudo apt-get install xsel
  - go test -v -short ./... -parallel 1
